services:
  initialarchitecture:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Contracts=Server=fitnetdb;Port=5432;Database=FitnedDb;User Id=postgres;Password=postgres
      - ConnectionStrings__Offers=Server=fitnetdb;Port=5432;Database=FitnedDb;User Id=postgres;Password=postgres
      - ConnectionStrings__Passes=Server=fitnetdb;Port=5432;Database=FitnedDb;User Id=postgres;Password=postgres
      - ConnectionStrings__Reports=Server=fitnetdb;Port=5432;Database=FitnedDb;User Id=postgres;Password=postgres
      # Override appsettings.json ConnectionStrings for each module 

    depends_on:
      - fitnetdb # Definisao sam u docker-compose.yml
    ports:
      - "6000:8080"
      - "6060:8081"
      # Levi port je initialarchitecture u Docker (6000 http, 6060 https) koji FE gadja. 
      # Desni port je initialarchitecture u Docker na koji se mapira levi port. 
      # U Docker rezimu, initialarchitecture koristi levi port da primi FE request (http://localhost:6000), a onda request mapira na desni port. 
      # App u Docker i Postgres u Docker ne zna se port preko kog pricaju, jer to Docker sam resava
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  fitnetdb:
    container_name: fitnedb # From docker-compose.yml
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FitnetDb
      # Ovo iznad je iz appsettings.json. Objasnjeno u EShopMicroservices
    restart: always
    ports:
      - "5432:5432" # Levi je initialarchitecture u localhost rezimu. Desni je fitnetdb docker port jer mora on za Postgres in Docker.
                    # InitialArchitecture koristi 5285(http) i 7223(https) da primi Request od FE, dok 5432 koristi za pricu sa fitnetdb docker koji takodje koristi 5432
    volumes:
      - postgres_initialarchitecture:/var/lib/postgresql/data